version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-test
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongo-test-net

  express:
    image: express
    build:
      context: "./api"
      dockerfile: Dockerfile
    container_name: express-test
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - mongo-test-net

  react:
    image: react
    build:
      context: "./app"
      dockerfile: Dockerfile
    container_name: react-test
    ports:
      - "3000:3000"
    depends_on:
      - express
    networks:
      - mongo-test-net

networks:
  mongo-test-net:
    driver: bridge
